export { default as Checkbox } from './Checkbox'
export { default as Switch } from './Switch'
export { default as InputNumber } from './Number'
export { default as InputText } from './Text'
export { default as InputBox } from './Box'
export { default as Select } from './Select'
export { default as CodeMirror } from './CodeMirror'
